import { Router } from "express";
import crypto from "crypto";
import { readDB, writeDB } from "../db.js";
import { authMiddleware } from "../middleware/auth.js";
import { publish } from "../tg_events.js";

const r = Router();

function trim(v){ return (v===null||v===undefined) ? "" : String(v).trim(); }
function now(){ return Date.now(); }
function newId(){ return crypto.randomBytes(16).toString("hex"); }
function code6(){ return String(Math.floor(100000 + Math.random()*900000)); }
function token32(){ return crypto.randomBytes(16).toString("hex"); }

function ensureCollections(db){
  if (!Array.isArray(db.tgOrgs)) db.tgOrgs = [];
  if (!Array.isArray(db.tgDevices)) db.tgDevices = [];
  if (!Array.isArray(db.tgEnrollTokens)) db.tgEnrollTokens = [];
  if (!Array.isArray(db.tgPairCodes)) db.tgPairCodes = [];
  if (!Array.isArray(db.tgCommands)) db.tgCommands = [];
  if (!Array.isArray(db.tgLocations)) db.tgLocations = [];
  if (!Array.isArray(db.tgHeartbeats)) db.tgHeartbeats = [];
  if (!Array.isArray(db.tgIntruders)) db.tgIntruders = [];
}

function upsertDevice(db, patch){
  const deviceId = trim(patch.deviceId);
  if (!deviceId) return null;
  let d = db.tgDevices.find(x => trim(x.deviceId) === deviceId);
  if (!d){
    d = {
      deviceId,
      paired:false,
      deviceKey:"",
      pairedAt:0,
      lastSeen:0,
      online:false,
      model:"",
      brand:"",
      sdk:"",
      appVersion:"",
      note:"",
      orgCode:"",
      mode:"LITE"
    };
    db.tgDevices.push(d);
  }
  Object.assign(d, patch);
  return d;
}

function safeListDevices(db, orgCode){
  const list = db.tgDevices
    .filter(d => !orgCode || trim(d.orgCode) === orgCode)
    .sort((a,b)=> (b.lastSeen||0)-(a.lastSeen||0));
  return list;
}

// ------------------- Admin auth (SuperPOSNG JWT) -------------------
function isAdminOrOwner(req){
  const role = (req?.auth?.role || "").toLowerCase();
  return role === "admin" || role === "owner";
}
function requireAdminJWT(req, res, next){
  authMiddleware(req, res, ()=>{
    if (!isAdminOrOwner(req)) return res.status(403).json({ ok:false, error:"forbidden" });
    next();
  });
}

// Dashboard-friendly admin auth:
// - Accept ?key=API_KEY (or header x-api-key) so TrackGuard dashboard can work even in Incognito
//   without relying on SuperPOS owner portal JWT in localStorage.
function requireAdminAccess(req, res, next){
  const apiKey = trim(process.env.API_KEY || "");
  const keyQ = trim(req.query?.key || "");
  const keyH = trim(req.headers["x-api-key"] || req.headers["X-API-Key"] || "");
  const key = keyQ || keyH;

  if (apiKey && key && key === apiKey) {
    // Minimal auth object for audit/debug
    req.auth = { role: "admin", sub: "API_KEY" };
    return next();
  }
  return requireAdminJWT(req, res, next);
}

// ------------------- Device auth (x-device-key) -------------------
function requireDeviceKey(req, res, next){
  const deviceId = trim(req.body?.deviceId || req.query?.deviceId || "");
  const key = trim(req.headers["x-device-key"] || req.headers["X-Device-Key"] || "");
  if (!deviceId) return res.status(400).json({ ok:false, error:"missing_deviceId" });
  if (!key) return res.status(401).json({ ok:false, error:"missing_device_key" });

  const db = readDB(); ensureCollections(db);
  const d = db.tgDevices.find(x => trim(x.deviceId) === deviceId);
  if (!d || !trim(d.deviceKey) || trim(d.deviceKey) !== key) {
    return res.status(401).json({ ok:false, error:"invalid_device_key" });
  }
  req.tgDevice = d;
  req.tgDB = db;
  next();
}

// ------------------- Public/device endpoints -------------------

// Pair confirm (device -> server). Uses pairCode generated by owner in dashboard.
r.post("/pair/confirm", (req,res)=>{
  const pairCode = trim(req.body?.pairCode || req.body?.code || "");
  const deviceId = trim(req.body?.deviceId);
  if (!pairCode) return res.status(400).json({ ok:false, error:"missing_pairCode" });
  if (!deviceId) return res.status(400).json({ ok:false, error:"missing_deviceId" });

  const db = readDB(); ensureCollections(db);

  // clean expired
  db.tgPairCodes = db.tgPairCodes.filter(x => (x.expAt||0) > now());
  const row = db.tgPairCodes.find(x => trim(x.pairCode)===pairCode && !x.used);
  if (!row) {
    writeDB(db);
    return res.status(404).json({ ok:false, error:"invalid_or_expired_pairCode" });
  }

  row.used = true;
  row.deviceId = deviceId;

  const deviceKey = token32();
  const d = upsertDevice(db, { deviceId, paired:true, deviceKey, pairedAt: now(), online:true, lastSeen: now() });
  writeDB(db);

  publish("paired", { deviceId, paired:true });
  return res.json({ ok:true, deviceKey });
});

// Optional pre-pair registration (works with enrollToken, for enterprise bulk)
r.post("/device/register", (req,res)=>{
  const deviceId = trim(req.body?.deviceId);
  if (!deviceId) return res.status(400).json({ ok:false, error:"missing_deviceId" });

  const enrollToken = trim(req.body?.enrollToken || "");
  const orgCode = trim(req.body?.orgCode || "");
  const mode = trim(req.body?.mode || "LITE").toUpperCase();

  const model = trim(req.body?.model || "");
  const brand = trim(req.body?.brand || "");
  const sdk = trim(req.body?.sdk || "");
  const appVersion = trim(req.body?.appVersion || "");

  const db = readDB(); ensureCollections(db);

  let finalOrg = "";
  if (enrollToken){
    const t = db.tgEnrollTokens.find(x => trim(x.token)===enrollToken && !x.used && (x.expAt||0) > now());
    if (!t) return res.status(401).json({ ok:false, error:"invalid_enrollToken" });
    finalOrg = trim(t.orgCode || "");
    t.used = true;
    t.usedAt = now();
    t.deviceId = deviceId;
  } else if (orgCode){
    finalOrg = orgCode;
  }

  const d = upsertDevice(db, { deviceId, orgCode: finalOrg, mode: mode || "LITE", model, brand, sdk, appVersion });
  writeDB(db);

  publish("device_registered", { deviceId, orgCode: finalOrg, mode: d.mode });
  return res.json({ ok:true, deviceId, orgCode: finalOrg, mode: d.mode });
});

// Heartbeat (device -> server) with x-device-key
r.post("/device/heartbeat", requireDeviceKey, (req,res)=>{
  const db = req.tgDB;
  const d = req.tgDevice;

  const model = trim(req.body?.model || "");
  const brand = trim(req.body?.brand || "");
  const sdk = trim(req.body?.sdk || "");
  const appVersion = trim(req.body?.appVersion || "");

  d.lastSeen = now();
  d.online = true;
  if (model) d.model = model;
  if (brand) d.brand = brand;
  if (sdk) d.sdk = sdk;
  if (appVersion) d.appVersion = appVersion;

  db.tgHeartbeats.push({ id:newId(), deviceId: d.deviceId, at: d.lastSeen, model:d.model, brand:d.brand, sdk:d.sdk, appVersion:d.appVersion });
  // trim
  if (db.tgHeartbeats.length > 5000) db.tgHeartbeats = db.tgHeartbeats.slice(db.tgHeartbeats.length-5000);

  writeDB(db);
  publish("heartbeat", { deviceId: d.deviceId, lastSeen: d.lastSeen });
  return res.json({ ok:true, lastSeen: d.lastSeen });
});

// Location push (device -> server)
r.post("/location/push", requireDeviceKey, (req,res)=>{
  const db = req.tgDB;
  const d = req.tgDevice;

  const lat = Number(req.body?.lat);
  const lng = Number(req.body?.lng);
  const accuracy = Number(req.body?.accuracy || 0);
  const source = trim(req.body?.source || "");
  if (!isFinite(lat) || !isFinite(lng)) return res.status(400).json({ ok:false, error:"missing_lat_lng" });

  const row = { id:newId(), deviceId:d.deviceId, at: now(), lat, lng, accuracy, source };
  db.tgLocations.push(row);
  if (db.tgLocations.length > 20000) db.tgLocations = db.tgLocations.slice(db.tgLocations.length-20000);
  writeDB(db);

  publish("location", { deviceId:d.deviceId, lat, lng, accuracy, at: row.at });
  return res.json({ ok:true });
});

// Device polls for next command
r.get("/command/poll", (req,res)=>{
  const deviceId = trim(req.query?.deviceId || "");
  const key = trim(req.headers["x-device-key"] || "");
  if (!deviceId) return res.status(400).json({ ok:false, error:"missing_deviceId" });
  if (!key) return res.status(401).json({ ok:false, error:"missing_device_key" });

  const db = readDB(); ensureCollections(db);
  const d = db.tgDevices.find(x => trim(x.deviceId) === deviceId);
  if (!d || trim(d.deviceKey) !== key) return res.status(401).json({ ok:false, error:"invalid_device_key" });

  const cmd = db.tgCommands.find(c => trim(c.deviceId)===deviceId && trim(c.status)==="PENDING");
  if (!cmd) return res.json({ ok:true, command:null });

  cmd.status = "SENT";
  cmd.sentAt = now();
  writeDB(db);

  publish("command_sent", { deviceId, commandId: cmd.id, type: cmd.type });
  return res.json({ ok:true, command: { id: cmd.id, type: cmd.type, payload: cmd.payload || {} } });
});

// Device sends command result / ack
r.post("/command/result", (req,res)=>{
  const deviceId = trim(req.body?.deviceId || "");
  const commandId = trim(req.body?.commandId || req.body?.id || "");
  const ok = !!req.body?.ok;
  const result = req.body?.result ?? req.body?.message ?? "";
  const key = trim(req.headers["x-device-key"] || "");
  if (!deviceId) return res.status(400).json({ ok:false, error:"missing_deviceId" });
  if (!commandId) return res.status(400).json({ ok:false, error:"missing_commandId" });
  if (!key) return res.status(401).json({ ok:false, error:"missing_device_key" });

  const db = readDB(); ensureCollections(db);
  const d = db.tgDevices.find(x => trim(x.deviceId)===deviceId);
  if (!d || trim(d.deviceKey)!==key) return res.status(401).json({ ok:false, error:"invalid_device_key" });

  const cmd = db.tgCommands.find(c => trim(c.id)===commandId && trim(c.deviceId)===deviceId);
  if (!cmd) return res.status(404).json({ ok:false, error:"command_not_found" });

  cmd.status = ok ? "DONE" : "FAILED";
  cmd.doneAt = now();
  cmd.result = String(result || "");
  writeDB(db);

  publish("command_result", { deviceId, commandId, ok, result: cmd.result });
  return res.json({ ok:true });
});

// ------------------- Admin endpoints -------------------

r.post("/org", requireAdminAccess, (req,res)=>{
  const name = trim(req.body?.name);
  const orgCode = trim(req.body?.orgCode) || ("ORG-" + code6());
  if (!name) return res.status(400).json({ ok:false, error:"missing_name" });

  const db = readDB(); ensureCollections(db);
  const exists = db.tgOrgs.find(o=> trim(o.orgCode)===orgCode);
  if (exists) return res.status(409).json({ ok:false, error:"org_exists" });

  const row = { orgCode, name, createdAt: now(), createdBy: trim(req.auth?.sub || req.auth?.userId || req.auth?.email || "") };
  db.tgOrgs.push(row);
  writeDB(db);
  publish("org_created", { orgCode, name });
  return res.json({ ok:true, org: row });
});

r.post("/enroll/token", requireAdminAccess, (req,res)=>{
  const orgCode = trim(req.body?.orgCode);
  if (!orgCode) return res.status(400).json({ ok:false, error:"missing_orgCode" });

  const ttlMinutes = Number(req.body?.ttlMinutes || 60);
  const expAt = now() + Math.max(5, ttlMinutes) * 60 * 1000;
  const token = token32();

  const db = readDB(); ensureCollections(db);
  db.tgEnrollTokens.push({ token, orgCode, expAt, createdAt: now(), used:false, usedAt:0, deviceId:"" });
  // trim
  db.tgEnrollTokens = db.tgEnrollTokens.filter(x => (x.expAt||0) > now());
  writeDB(db);
  publish("enroll_token", { orgCode });
  return res.json({ ok:true, token, expAt });
});

r.get("/org/:orgCode/devices", requireAdminAccess, (req,res)=>{
  const orgCode = trim(req.params.orgCode);
  const db = readDB(); ensureCollections(db);
  return res.json({ ok:true, devices: safeListDevices(db, orgCode) });
});

r.get("/devices", requireAdminAccess, (req,res)=>{
  const db = readDB(); ensureCollections(db);
  return res.json({ ok:true, devices: safeListDevices(db, "") });
});

r.post("/pair/generate", requireAdminAccess, (req,res)=>{
  const db = readDB(); ensureCollections(db);
  const pairCode = code6();
  const expAt = now() + 10*60*1000; // 10 minutes
  db.tgPairCodes.push({ pairCode, expAt, createdAt: now(), used:false, deviceId:"" });
  // trim
  db.tgPairCodes = db.tgPairCodes.filter(x => (x.expAt||0) > now());
  writeDB(db);
  publish("pair_code", { code: pairCode, expiresAt: expAt });
  return res.json({ ok:true, pairCode, expAt });
});

r.post("/command/send", requireAdminAccess, (req,res)=>{
  const deviceId = trim(req.body?.deviceId);
  const type = trim(req.body?.type).toUpperCase();
  const payload = req.body?.payload ?? {};
  if (!deviceId) return res.status(400).json({ ok:false, error:"missing_deviceId" });
  if (!type) return res.status(400).json({ ok:false, error:"missing_type" });

  const db = readDB(); ensureCollections(db);
  upsertDevice(db, { deviceId }); // ensure exists
  const cmd = { id:newId(), deviceId, type, payload, status:"PENDING", createdAt: now(), sentAt:0, doneAt:0, result:"" };
  db.tgCommands.push(cmd);
  if (db.tgCommands.length > 20000) db.tgCommands = db.tgCommands.slice(db.tgCommands.length-20000);
  writeDB(db);

  publish("command_queued", { deviceId, commandId: cmd.id, type });
  return res.json({ ok:true, commandId: cmd.id });
});


// ------------------- Admin read helpers (for Dashboard) -------------------
function getDeviceOrNull(db, deviceId){
  const id = trim(deviceId);
  if (!id) return null;
  return db.tgDevices.find(x => trim(x.deviceId) === id) || null;
}

// Location trail (admin) - used by dashboard map
function handleLocationTrail(req, res){
  const db = readDB(); ensureCollections(db);
  const deviceId = trim(req.query?.deviceId || "");
  const limit = Math.max(1, Math.min(1000, parseInt(req.query?.limit || "200", 10) || 200));
  const list = db.tgLocations
    .filter(x => !deviceId || trim(x.deviceId) === deviceId)
    .sort((a,b)=> (b.ts||0)-(a.ts||0))
    .slice(0, limit);
  return res.json({ ok:true, items:list });
}
r.get("/location/trail", requireAdminAccess, handleLocationTrail);
// Backward-compat: dashboard older build calls /api/location/trail
r.get("/api/location/trail", requireAdminAccess, handleLocationTrail);

// Commands list (admin) - dashboard reads queued/recent commands
function handleCommandsList(req, res){
  const db = readDB(); ensureCollections(db);
  const deviceId = trim(req.query?.deviceId || "");
  const limit = Math.max(1, Math.min(2000, parseInt(req.query?.limit || "200", 10) || 200));
  const list = db.tgCommands
    .filter(x => !deviceId || trim(x.deviceId) === deviceId)
    .sort((a,b)=> (b.ts||0)-(a.ts||0))
    .slice(0, limit);
  return res.json({ ok:true, items:list });
}
r.get("/commands", requireAdminAccess, handleCommandsList);
r.get("/api/commands", requireAdminAccess, handleCommandsList);

// Intruder list (admin) - optional; returns empty if none
function handleIntruderList(req, res){
  const db = readDB(); ensureCollections(db);
  const deviceId = trim(req.query?.deviceId || "");
  const limit = Math.max(1, Math.min(200, parseInt(req.query?.limit || "50", 10) || 50));
  const list = db.tgIntruders
    .filter(x => !deviceId || trim(x.deviceId) === deviceId)
    .sort((a,b)=> (b.ts||0)-(a.ts||0))
    .slice(0, limit);
  return res.json({ ok:true, items:list });
}
r.get("/intruder/list", requireAdminAccess, handleIntruderList);
r.get("/api/intruder/list", requireAdminAccess, handleIntruderList);

// Device can push intruder snapshot/event (optional)
r.post("/intruder/push", requireDeviceKey, (req, res) => {
  const db = req.tgDB; ensureCollections(db);
  const deviceId = trim(req.body?.deviceId || "");
  const kind = trim(req.body?.kind || "SNAP");
  const image = trim(req.body?.image || ""); // base64 data URL recommended
  const note = trim(req.body?.note || "");
  const item = { id:newId(), deviceId, kind, image, note, ts: now() };
  db.tgIntruders.push(item);
  // keep last 2000
  if (db.tgIntruders.length > 2000) db.tgIntruders = db.tgIntruders.slice(db.tgIntruders.length-2000);
  writeDB(db);
  publish("intruder", { deviceId, id:item.id, kind });
  return res.json({ ok:true, id:item.id });
});

export default r;
